# Do NOT update manually; changes here will be overwritten by Copier
_commit: 0f6de6d
_src_path: gh:open-synergy/ssi-addons-repo-template
dependency_installation_mode: OCA
generate_requirements_txt: false
include_aeroo_report: false
include_wkhtmltopdf: true
odoo_version: 8.0
rebel_module_groups: []
repo_description: opnsynid-l10n-indonesia-djbc-fullfilment-service
repo_name: opnsynid-l10n-indonesia-djbc-fullfilment-service
repo_slug: opnsynid-l10n-indonesia-djbc-fullfilment-service
travis_apt_packages: []
travis_apt_sources: []
